[WIP] Add I2C slave.
stm32-rs/stm32f0xx-hal pull request #124
Opened 2020-11-10 19:57 UTC by matoushybl

This adds an I2C slave implementation for I2C1 that I developed for use in a personal project. This is a very much WIP as no support for I2C2 is available and the code is not compliant with anything in embedded-hal.

It'd be nice if this could be discussed here what can be done to make this code mergeable as there are almost none examples of implementing I2C slave for STM32 and other controllers.

2021-04-25 21:06 UTC, therealprof requested changes
Hi there 👋.

Thanks for this PR. I think with 3 more changes we can merge this:

- [ ] Address the commented out code, including potentially adding some more commentary
- [ ] Add a CHANGELOG entry
- [ ] Add example code so people can directly try the slave functionality

2025-12-24 11:55 UTC, quarthex requested changes
This feature would be a great addition to the crate.
Thanks for your work. :+1:

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +            self.transfer_buffer[index] = *item;
This may panic since `buffer` can be wider than `self.transfer_buffer`.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +#[derive(PartialEq)]
You should derive from `Eq`, since there is no way for `a == b` being different from `b == a`.
Also make your public types derive from `Debug`, since developers may try to debug their stuff.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +pub enum TransferState {
Add a brief documentation for every public type + each of its variant.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +// direction as specified in the datasheet
This comment could be promoted to documentation (`///`).

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +impl From<Direction> for bool {
Public conversion from a direction to `bool` does not make much sense. What does a `true` direction mean?
In my opinion, you should use `dir == Direction::Read` for raw bits.
A `Direction::is_read()` would be even cleaner.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +            w.nostretch()
This looooong call list would be easier to handle if each setting were on its own line.
Something like:
```rs
w.nostretch().enabled(); // enable clock stretching
w.anfoff().enabled(); // enable analog filter
w.dnf().no_filter(); // disable digital filter
...
```
There is no performance issue writing this that way.
This remark applies to following register updates.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +    pub fn is_status(&self, status: Status, clear: bool) -> bool {
There are a lot of unnecessary `return`s.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +impl<I2C, SCL, SDA> I2CSlave<I2C, SCL, SDA>
All public methods should be documented.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +        }
This can be merged with a single or-condition.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +            }
A `match` would be more readable.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +            if self.transfer_state == TransferState::RegisterSet {
Merge the conditions.

2025-12-24 11:55 UTC, quarthex commented on src/i2c_slave.rs
> +            if self.transfer_state == TransferState::Transmitting {
Merge the conditions.

2026-01-03 10:00 UTC, matoushybl commented
@quarthex Thanks for the review! This pull request is more than 6 years old, I no longer work with F0s nor do I plan to. If you have a use case for it, you can take over or reimplement it from scratch (given the low code quality). 
For a sample implementation, you can have a look at embassy-stm32 which recently added I2C slave support.

2026-01-03 10:00 UTC, closed without merging