[WIP] Add CAN bus.
stm32-rs/stm32f0xx-hal pull request #125
Opened 2020-11-10 20:07 UTC by matoushybl

Adds CAN bus as I developed it for my project.

Any feedback is welcome. I'll continue the development to make it fully working in context of the HAL.

Also CAN traits are under review in embedded-hal, so I might implement the traits before they are merged for future compatibility.

2020-11-14 13:18 UTC, jonas-schievink commented on src/i2c_slave.rs
> +}
Unrelated change?

2020-11-14 13:18 UTC, jonas-schievink commented on src/lib.rs
> +    feature = "stm32f091",
```suggestion
    feature = "stm32f091",
    feature = "stm32f042",
    feature = "stm32f072",
```

That's all of them according to the ST website.

2020-11-14 20:06 UTC, matoushybl commented
Hi, @jonas-schievink! Thanks for the review! I have fixed the problems you've found and generally fixed some problems with the code. It is still not mergeable to master (pin definitions are still not implemented), but I expect to finish it sometime next week.

2020-11-17 19:29 UTC, therealprof requested changes
Missing a CHANGELOG entry. ;)

2020-11-19 22:14 UTC, therealprof approved these changes
Haven't had a chance to test it out in person but let's get this in so people can play with it.

Thanks a lot!

bors r+

2020-11-19 22:27 UTC, merged